[package]
name = "fs-unpack-dll"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
argh = "0.1.13"
base64ct = { version = "1.8.0", features = ["alloc"] }
miniz_oxide = { version = "0.8.9", features = ["alloc"] }
fs-lib = { version = "1.0.0", path = "../fs-lib" }